import { useMemo, useState } from 'react';
import { Check, ChevronDown, Lightbulb, Sparkles, WandSparkles } from 'lucide-react';
import { Button } from '../../../components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from '../../../components/animate-ui/components/radix/dropdown-menu';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../../../components/ui/dialog';
import { cn } from '../../../utils';

type Nivel = 'alta' | 'media' | 'revisao';
type Sugestao = { id: string; gaveta: string; itens: { nome: string; detalhe: string; valor: string }[]; nivel: Nivel; motivo: string };

const SUGESTOES: Sugestao[] = [
  { id: 'freio-cg125', gaveta: 'Freio dianteiro · CG 125 Titan', nivel: 'alta', motivo: 'Categoria compatível + modelo CG 125 + período 1995 a 1999', itens: [{ nome: 'Tampa do cubo CG 125', detalhe: 'Freio dianteiro · 2 un.', valor: 'R$ 65,00' }, { nome: 'Disco de freio CG 125', detalhe: 'Freio dianteiro · 1 un.', valor: 'R$ 80,00' }, { nome: 'Pastilha de freio CG 125', detalhe: 'Freio dianteiro · 4 un.', valor: 'R$ 35,00' }] },
  { id: 'embreagem-cg150', gaveta: 'Embreagem · CG 150 Carburada', nivel: 'media', motivo: 'Nome semelhante + modelo CG 150; ano não informado', itens: [{ nome: 'Discos de embreagem CG 150', detalhe: 'Embreagem · 8 un.', valor: 'R$ 60,00' }, { nome: 'Tampa da embreagem CG 150', detalhe: 'Embreagem · 1 un.', valor: 'R$ 180,00' }] },
  { id: 'sem-classificacao', gaveta: 'Sugestão pendente de revisão', nivel: 'revisao', motivo: 'O item pode pertencer a mais de uma gaveta', itens: [{ nome: 'Suporte lateral CG', detalhe: 'Categoria não informada · 1 un.', valor: 'R$ 45,00' }] },
];

const nivelConfig: Record<Nivel, { label: string; className: string }> = { alta: { label: 'Alta confiança', className: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' }, media: { label: 'Boa correspondência', className: 'bg-amber-500/10 text-amber-200 border-amber-500/20' }, revisao: { label: 'Revisão necessária', className: 'bg-orange-500/10 text-orange-200 border-orange-500/20' } };

export function OrganizacaoAssistidaPreview({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [filtro, setFiltro] = useState<Nivel | 'todas'>('todas');
  const [revisando, setRevisando] = useState<Sugestao | null>(null);
  const sugestoes = useMemo(() => filtro === 'todas' ? SUGESTOES : SUGESTOES.filter((item) => item.nivel === filtro), [filtro]);

  return <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="z-[70] max-h-[min(90vh,52rem)] max-w-3xl overflow-y-auto p-0">
      <DialogHeader className="border-b border-border-subtle px-5 py-5 text-left sm:px-6">
        <div className="flex items-start gap-3 pr-6"><div className="flex size-10 shrink-0 items-center justify-center rounded-card bg-accent-soft text-accent-soft-fg"><WandSparkles size={19} /></div><div><DialogTitle className="text-xl">Organização assistida</DialogTitle><DialogDescription className="mt-1">Sugestões para organizar itens sem gaveta. Você confirma cada movimentação.</DialogDescription></div></div>
        <div className="mt-4 grid grid-cols-3 gap-2">{[['384', 'pendentes'], ['72', 'sugestões'], ['18', 'revisões']].map(([valor, label]) => <div key={label} className="rounded-control border border-border-subtle bg-surface-inset px-3 py-2"><p className="text-lg font-bold text-text-primary">{valor}</p><p className="text-[10px] font-semibold uppercase tracking-wider text-text-muted">{label}</p></div>)}</div>
        <p className="mt-2 text-[11px] text-text-faint">Prévia visual com dados demonstrativos — nenhuma peça será movida nesta tela.</p>
      </DialogHeader>
      <div className="space-y-3 px-5 py-4 sm:px-6">
        <div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold text-text-primary">Sugestões encontradas</p><p className="text-xs text-text-muted">Agrupadas por destino para acelerar a conferência.</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm">{filtro === 'todas' ? 'Todas as sugestões' : nivelConfig[filtro].label}<ChevronDown size={14} /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-56"><DropdownMenuLabel>Filtrar confiança</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuRadioGroup value={filtro} onValueChange={(value) => setFiltro(value as Nivel | 'todas')}><DropdownMenuRadioItem value="todas">Todas as sugestões</DropdownMenuRadioItem><DropdownMenuRadioItem value="alta">Alta confiança</DropdownMenuRadioItem><DropdownMenuRadioItem value="media">Boa correspondência</DropdownMenuRadioItem><DropdownMenuRadioItem value="revisao">Revisão necessária</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></div>
        <div className="space-y-3">{sugestoes.map((sugestao) => { const config = nivelConfig[sugestao.nivel]; return <article key={sugestao.id} className="rounded-card border border-border-default bg-surface-card p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-text-primary">{sugestao.gaveta}</h3><span className={cn('rounded-full border px-2 py-0.5 text-[10px] font-semibold', config.className)}>{config.label}</span></div><p className="mt-1 flex items-center gap-1 text-xs text-text-muted"><Lightbulb size={13} className="text-accent" />{sugestao.motivo}</p></div><span className="text-xs font-semibold text-text-muted">{sugestao.itens.length} itens</span></div><div className="mt-3 divide-y divide-border-subtle rounded-control border border-border-subtle bg-surface-inset">{sugestao.itens.map((item) => <div key={item.nome} className="grid grid-cols-[auto_auto_minmax(0,1fr)_auto] items-start gap-2 px-3 py-2.5"><span className="mt-0.5 flex size-4 items-center justify-center rounded border border-border-default bg-surface-card" aria-hidden="true" /><div className="flex size-8 items-center justify-center rounded-control bg-surface-raised text-text-faint"><Sparkles size={14} /></div><div className="min-w-0"><p className="break-words text-sm font-semibold leading-snug text-text-primary">{item.nome}</p><p className="break-words text-xs text-text-muted">{item.detalhe}</p></div><span className="whitespace-nowrap text-sm font-semibold text-text-primary">{item.valor}</span></div>)}</div><div className="mt-3 flex flex-wrap justify-end gap-2"><Button variant="ghost" size="sm">Ignorar</Button><Button variant="outline" size="sm" onClick={() => setRevisando(sugestao)}>Revisar</Button>{sugestao.nivel !== 'revisao' && <Button variant="accent-cta" size="sm"><Check size={14} /> Aceitar grupo</Button>}</div></article>; })}</div>
      </div>
      <DialogFooter className="border-t border-border-subtle px-5 py-4 sm:px-6"><Button variant="outline" onClick={() => onOpenChange(false)}>Fechar prévia</Button></DialogFooter>
    </DialogContent>
    <Dialog open={!!revisando} onOpenChange={(aberto) => !aberto && setRevisando(null)}><DialogContent className="z-[80] max-w-md"><DialogHeader><DialogTitle>Revisar sugestão</DialogTitle><DialogDescription>{revisando?.gaveta}</DialogDescription></DialogHeader><div className="space-y-2"><p className="text-xs font-semibold uppercase tracking-wider text-text-muted">Outros destinos possíveis</p>{['Freio dianteiro · CG 125 Titan', 'Peças gerais · CG 125', 'Sem gaveta'].map((destino, index) => <button key={destino} type="button" className={cn('flex w-full items-center justify-between rounded-control border px-3 py-3 text-left text-sm', index === 0 ? 'border-accent bg-accent-soft text-text-primary' : 'border-border-default text-text-muted hover:bg-surface-raised')}>{destino}{index === 0 && <Check size={15} />}</button>)}</div><DialogFooter><Button variant="outline" onClick={() => setRevisando(null)}>Cancelar</Button><Button variant="accent-cta" onClick={() => setRevisando(null)}>Confirmar destino</Button></DialogFooter></DialogContent></Dialog>
  </Dialog>;
}
